Repository doctrine/annotations, pull requests merged in 2018-05, with the labels that each got.

#198 Fix package name to doctrine/annotations
  docs/en/index.rst
Labels: Documentation

#200 Drop copyright headers
  lib/Doctrine/Annotations/Annotation.php
  lib/Doctrine/Annotations/Annotation/Attribute.php
  lib/Doctrine/Annotations/Annotation/Attributes.php
  lib/Doctrine/Annotations/Annotation/Enum.php
  lib/Doctrine/Annotations/Annotation/IgnoreAnnotation.php
  lib/Doctrine/Annotations/Annotation/Required.php
  lib/Doctrine/Annotations/Annotation/Target.php
  lib/Doctrine/Annotations/AnnotationException.php
  lib/Doctrine/Annotations/AnnotationReader.php
  lib/Doctrine/Annotations/AnnotationRegistry.php
  lib/Doctrine/Annotations/CachedReader.php
  lib/Doctrine/Annotations/DocLexer.php
  lib/Doctrine/Annotations/DocParser.php
  lib/Doctrine/Annotations/FileCacheReader.php
  lib/Doctrine/Annotations/IndexedReader.php
  lib/Doctrine/Annotations/PhpParser.php
  lib/Doctrine/Annotations/Reader.php
  lib/Doctrine/Annotations/SimpleAnnotationReader.php
  lib/Doctrine/Annotations/TokenParser.php
  tests/Doctrine/Tests/Annotations/Annotation/TargetTest.php
Labels: Improvement

#201 Update namespace in docs
  docs/en/annotations.rst
Labels: Documentation

#203 1.6 docs
  docs/en/annotations.rst
  docs/en/custom.rst
  docs/en/index.rst
  docs/en/sidebar.rst
Labels: Documentation

#205 Eliminate AnnotationRegistry, rely on autoloading only
  docs/en/annotations.rst
  docs/en/custom.rst
  lib/Doctrine/Annotations/AnnotationReader.php
  lib/Doctrine/Annotations/AnnotationRegistry.php
  lib/Doctrine/Annotations/DocParser.php
  phpunit.xml.dist
  tests/Doctrine/Tests/Annotations/AnnotationRegistryTest.php
  tests/Doctrine/Tests/Annotations/DocParserTest.php
  tests/Doctrine/Tests/TestInit.php
Labels: BC-Break, Improvement

#206 Add Scrutinizer CI
  .scrutinizer.yml
  .travis.yml
  composer.json
Labels: CI

#202 Drop deprecated FileCacheReader
  UPGRADE.md
  docs/en/annotations.rst
  lib/Doctrine/Annotations/FileCacheReader.php
  tests/Doctrine/Tests/Annotations/FileCacheReaderTest.php
  tests/Doctrine/Tests/Annotations/PerformanceTest.php
Labels: BC-Break, Improvement

#199 Drop SimpleAnnotationReader
  UPGRADE.md
  lib/Doctrine/Annotations/SimpleAnnotationReader.php
  tests/Doctrine/Tests/Annotations/SimpleAnnotationReaderTest.php
  tests/Doctrine/Tests/Annotations/Ticket/DCOM58Test.php
Labels: BC-Break, Improvement

#208 Fixed typo in the documentation
  docs/en/annotations.rst
Labels: Documentation

#209 Change Annotation::value typehint to mixed
  lib/Doctrine/Annotations/Annotation.php
Labels: bug
