Repository doctrine/annotations, pull requests merged in 2019-02, with the labels that each got.

#241 CI: Test against PHP 7.4snapshot instead of nightly (8.0)
  .travis.yml
Labels: CI

#237 [docs, 1.6] Fixed a wrong introduction sample code
  docs/en/index.rst
Labels: Documentation, wontfix

#242 Extract implicitly ignored annotation names to separate class
  lib/Doctrine/Annotations/AnnotationReader.php
  lib/Doctrine/Annotations/ImplicitlyIgnoredAnnotationNames.php
Labels: Improvement

#248 Convert performance tests to PHPBench
  .gitignore
  .travis.yml
  composer.json
  phpbench.json.dist
  phpunit.xml.dist
  tests/Doctrine/Performance/Annotations/CachedReadPerformanceWithInMemoryBench.php
  tests/Doctrine/Performance/Annotations/DocLexerPerformanceBench.php
  tests/Doctrine/Performance/Annotations/DocParsePerformanceBench.php
  tests/Doctrine/Performance/Annotations/MethodInitializer.php
  tests/Doctrine/Performance/Annotations/PhpParserPerformanceWithShortCutBench.php
  tests/Doctrine/Performance/Annotations/PhpParserPerformanceWithoutShortCutBench.php
  tests/Doctrine/Performance/Annotations/ReadPerformanceBench.php
  tests/Doctrine/Tests/Annotations/PerformanceTest.php
Labels: Improvement

#246 Drop base Annotation ancestor
  UPGRADE.md
  lib/Doctrine/Annotations/Annotation.php
  tests/Doctrine/Tests/Annotations/AbstractReaderTest.php
  tests/Doctrine/Tests/Annotations/AnnotationTest.php
  tests/Doctrine/Tests/Annotations/DocParserTest.php
  tests/Doctrine/Tests/Annotations/TopLevelAnnotation.php
Labels: BC-Break, Improvement

#249 Drop CachedReader
  UPGRADE.md
  composer.json
  lib/Doctrine/Annotations/CachedReader.php
  tests/Doctrine/Performance/Annotations/CachedReadPerformanceWithInMemoryBench.php
  tests/Doctrine/Tests/Annotations/CachedReaderTest.php
Labels: BC-Break, RFC

#250 Backport conversion of performance tests to PHPBench into 1.7
  .gitignore
  .travis.yml
  composer.json
  phpbench.json.dist
  phpunit.xml.dist
  tests/Doctrine/Performance/Common/Annotations/CachedReadPerformanceWithInMemoryBench.php
  tests/Doctrine/Performance/Common/Annotations/DocLexerPerformanceBench.php
  tests/Doctrine/Performance/Common/Annotations/DocParserPerformanceBench.php
  tests/Doctrine/Performance/Common/Annotations/MethodInitializer.php
  tests/Doctrine/Performance/Common/Annotations/PhpParserPerformanceWithShortCutBench.php
  tests/Doctrine/Performance/Common/Annotations/PhpParserPerformanceWithoutShortCutBench.php
  tests/Doctrine/Performance/Common/Annotations/ReadPerformanceBench.php
  tests/Doctrine/Performance/Common/bootstrap.php
  tests/Doctrine/Tests/Common/Annotations/PerformanceTest.php
Labels: Improvement

#251 Fix running PHPBench on Travis
  .travis.yml
Labels: Improvement
