Repository doctrine/annotations, pull requests merged in 2019-10, with the labels that each got.

#281 Backporting adding global ignored annotations to DocParser.
  lib/Doctrine/Common/Annotations/AnnotationReader.php
  tests/Doctrine/Tests/Common/Annotations/AnnotationReaderTest.php
Labels: enhancement

#280 Backporting ignoring PHP CodeSniffer annotations to 1.8.
  lib/Doctrine/Common/Annotations/AnnotationReader.php
  tests/Doctrine/Tests/Common/Annotations/AnnotationReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/ClassWithPHPCodeSnifferAnnotation.php
Labels: enhancement

#287 No longer require dev versions of PHPUnit on PHP 7.4
  .travis.yml
Labels: Improvement

#286 Fix PHPStan failures
  phpstan.neon.dist
  tests/Doctrine/Tests/Annotations/AbstractReaderTest.php
  tests/Doctrine/Tests/Annotations/AnnotationReaderTest.php
Labels: Hacktoberfest
