Repository doctrine/annotations, pull requests merged in 2019-01, with the labels that each got.

#236 CI: Use Ubuntu 16.04
  .travis.yml
Labels: CI, Improvement

#235 Update AnnotationReader's metadata parser to use list of known ignored annotation
  lib/Doctrine/Annotations/AnnotationReader.php
  tests/Doctrine/Tests/Annotations/AbstractReaderTest.php
Labels: bug

#239 Mention coding standard requirements in the README
  README.md
Labels: Documentation
