Repository doctrine/annotations, pull requests merged in 2019-03, with the labels that each got.

#247 Introduce annotation metadata
  lib/Doctrine/Annotations/Annotation/Target.php
  lib/Doctrine/Annotations/DocParser.php
  lib/Doctrine/Annotations/Metadata/AnnotationMetadata.php
  lib/Doctrine/Annotations/Metadata/AnnotationTarget.php
  lib/Doctrine/Annotations/Metadata/Builder/AnnotationMetadataBuilder.php
  lib/Doctrine/Annotations/Metadata/Builder/PropertyMetadataBuilder.php
  lib/Doctrine/Annotations/Metadata/Exception/InvalidAnnotationTarget.php
  lib/Doctrine/Annotations/Metadata/Exception/MetadataAlreadyExists.php
  lib/Doctrine/Annotations/Metadata/Exception/MetadataDoesNotExist.php
  lib/Doctrine/Annotations/Metadata/Exception/TooManyDefaultProperties.php
  lib/Doctrine/Annotations/Metadata/InternalAnnotations.php
  lib/Doctrine/Annotations/Metadata/MetadataCollection.php
  lib/Doctrine/Annotations/Metadata/PropertyMetadata.php
  lib/Doctrine/Annotations/Metadata/TransientMetadataCollection.php
  tests/Doctrine/Tests/Annotations/Metadata/AnnotationTargetTest.php
  tests/Doctrine/Tests/Annotations/Metadata/Builder/AnnotationMetadataBuilderTest.php
  tests/Doctrine/Tests/Annotations/Metadata/Builder/AnnotationMetadataTest.php
  tests/Doctrine/Tests/Annotations/Metadata/Builder/PropertyMetadataBuilderTest.php
  tests/Doctrine/Tests/Annotations/Metadata/TransientMetadataCollectionTest.php
Labels: Improvement, RFC

#255 phpstan updated to 0.11.3
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/Annotations/Annotation/Attributes.php
  lib/Doctrine/Annotations/Annotation/Target.php
  lib/Doctrine/Annotations/TokenParser.php
  phpstan.neon
  phpstan.neon.dist
Labels: enhancement

#257 Skip parsing annotations containing dashes, such as `@Foo-bar`, or `@Foo-`
  .travis.yml
  lib/Doctrine/Common/Annotations/DocLexer.php
  lib/Doctrine/Common/Annotations/DocParser.php
  tests/Doctrine/Tests/Common/Annotations/AbstractReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/DocLexerTest.php
  tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/ClassWithAnnotationConstantReferenceWithDashes.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/ClassWithInvalidAnnotationContainingDashes.php
Labels: bug

#259 Use void where applicable in the tests directory
  tests/Doctrine/Tests/Annotations/AbstractReaderTest.php
  tests/Doctrine/Tests/Annotations/Annotation/TargetTest.php
  tests/Doctrine/Tests/Annotations/AnnotationReaderTest.php
  tests/Doctrine/Tests/Annotations/DocParserTest.php
  tests/Doctrine/Tests/Annotations/DummyClass.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassOverwritesTrait.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassUsesTrait.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassWithAnnotationEnum.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassWithAnnotationWithTargetSyntaxError.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassWithAnnotationWithVarType.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassWithInvalidAnnotationTargetAtMethod.php
  tests/Doctrine/Tests/Annotations/Fixtures/ClassWithValidAnnotationTarget.php
  tests/Doctrine/Tests/Annotations/Fixtures/Controller.php
  tests/Doctrine/Tests/Annotations/Fixtures/IgnoredNamespaces/AnnotatedAtMethodLevel.php
  tests/Doctrine/Tests/Annotations/Fixtures/NamespaceWithClosureDeclaration.php
  tests/Doctrine/Tests/Annotations/Fixtures/TraitWithAnnotatedMethod.php
  tests/Doctrine/Tests/Annotations/PhpParserTest.php
  tests/Doctrine/Tests/Annotations/Ticket/DCOM55Test.php
  tests/Doctrine/Tests/Annotations/Ticket/DCOM58Test.php
Labels: Improvement

#254 Add all PHPUnit annotations to the globally ignored list
  lib/Doctrine/Annotations/ImplicitlyIgnoredAnnotationNames.php
Labels: Improvement

#261 Make phpdoc comments accurate
  lib/Doctrine/Annotations/DocParser.php
  lib/Doctrine/Annotations/Metadata/AnnotationMetadata.php
  lib/Doctrine/Annotations/Metadata/Builder/PropertyMetadataBuilder.php
  lib/Doctrine/Annotations/Metadata/PropertyMetadata.php
Labels: Improvement
