Repository doctrine/annotations, pull requests merged in 2020-04, with the labels that each got.

#316 Fix checks for ignored annotations
  lib/Doctrine/Common/Annotations/DocParser.php
  tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
Labels: bug

#271 Trigger the standard autoloader as the last resort
  lib/Doctrine/Common/Annotations/AnnotationRegistry.php
  tests/Doctrine/Tests/Common/Annotations/AnnotationRegistryTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/Annotation/CanBeAutoLoaded.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/Annotation/LoadedUsingRegisterFile.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/Annotation/ShouldNeverBeLoaded.php
Labels: Improvement

#318 Fix ignoring imported ignored annotations
  lib/Doctrine/Common/Annotations/DocParser.php
  tests/Doctrine/Tests/Common/Annotations/AnnotationReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/Annotation/Param.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/ClassWithImportedIgnoredAnnotation.php
Labels: bug

#320 Fix duplicate text in documentation
  docs/en/index.rst
Labels: Documentation

#322 Update website metadata for master branch
  .doctrine-project.json
Labels: Documentation

#323 Fix broken autoloading due to Reader calling registerFile
  lib/Doctrine/Common/Annotations/AnnotationReader.php
  lib/Doctrine/Common/Annotations/DocParser.php
Labels: bug

#326 Update index.rst
  docs/en/index.rst
Labels: Documentation
