Repository doctrine/annotations, pull requests merged in 2021-01, with the labels that each got.

#392 Ignore .phpunit.result.cache
  .gitignore
Labels: enhancement

#289 Add support for loading annotations from functions
  composer.json
  docs/en/custom.rst
  docs/en/index.rst
  lib/Doctrine/Common/Annotations/Annotation/Target.php
  lib/Doctrine/Common/Annotations/AnnotationReader.php
  lib/Doctrine/Common/Annotations/PhpParser.php
  phpcs.xml.dist
  tests/Doctrine/Tests/Common/Annotations/AnnotationReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/functions.php
Labels: Improvement

#391 Introduced annotation NamedArgumentConstructor
  docs/en/custom.rst
  lib/Doctrine/Common/Annotations/Annotation/NamedArgumentConstructor.php
  lib/Doctrine/Common/Annotations/DocParser.php
  tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
Labels: New Feature
