Repository doctrine/annotations, pull requests merged in 2022-10, with the labels that each got.

#453 Encourage migration towards attributes
  README.md
  composer.json
  docs/en/index.rst
Labels: Documentation

#454 Bump GHA workflows
  .github/workflows/coding-standards.yml
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#455 Doctrine CS 10
  composer.json
  lib/Doctrine/Common/Annotations/Annotation.php
  lib/Doctrine/Common/Annotations/AnnotationException.php
  lib/Doctrine/Common/Annotations/CachedReader.php
  lib/Doctrine/Common/Annotations/DocParser.php
  lib/Doctrine/Common/Annotations/TokenParser.php
  phpcs.xml.dist
  tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
Labels: Code Style

#459 Added test cases for enums
  tests/Doctrine/Tests/Common/Annotations/AnnotationReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/AnnotationWithEnumProperty.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/ClassWithEnumAnnotations.php
  tests/Doctrine/Tests/Common/Annotations/Fixtures/Suit.php
Labels: Test Suite
