Repository doctrine/annotations, pull requests merged in 2024-09, with the labels that each got.

#495 Ignore complaints about dead code
  psalm.xml
Labels: Static Analysis

#446 Convert ini_get result to bool before evaluating
  lib/Doctrine/Common/Annotations/AnnotationReader.php
Labels: bug

#497 Bump CI actions
  .github/workflows/coding-standards.yml
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#486 Extend deprecation notice
  README.md
  docs/en/index.rst
Labels: Documentation

#499 Test with Symfony Cache 7
  composer.json
Labels: Test Suite

#494 Fix filemtime() warning because of eval'd code
  lib/Doctrine/Common/Annotations/CachedReader.php
  lib/Doctrine/Common/Annotations/PsrCachedReader.php
  tests/Doctrine/Tests/Common/Annotations/CachedReaderTest.php
  tests/Doctrine/Tests/Common/Annotations/PsrCachedReaderTest.php
Labels: bug

#501 Doc fixes
  docs/en/index.rst
  docs/en/sidebar.rst
Labels: Documentation

#502 Setup documentation workflow
  .github/workflows/documentation.yml
Labels: CI
